[package]
name = "orchestrating-migrating-computations-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
paho-mqtt = "0.13.3"
futures = "0.3.31"
libc = "0.2.174"
wasmtime = "31.0.0"
wasmtime-wasi = "31.0.0"
