[package]
name = "sporadic_server"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "1.0.0-alpha.1"

[[bin]]
name = "sporadic_server"
path = "src/main.rs"

[features]
default = []
print_log = []
ss_timing_log = []